version: 2.1
orbs:
  gimlet: gimlet-io/circleci-orb@4.0.0

workflows:
  master-build:
    jobs:
      - test: {}
      - build_docker:
          requires:
            - test
      - gimlet/gimlet-artifact-push:
          name: 🚀 Deploy / Staging
          deploy: "true"
          env: "staging"
          app: "cis"
          requires:
            - build_docker

jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo testing

  build_docker:
    docker:
      - image: cimg/base:2021.04
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout
      - run:
          name: Building Docker image
          command: |
            LATEST_COMMIT=$(git rev-parse HEAD)
            docker login ghcr.io -u laszlocph -p $PAT
            docker build -t ghcr.io/gimlet-io/cis:$LATEST_COMMIT .
            docker push ghcr.io/gimlet-io/cis:$LATEST_COMMIT
