version: 2.1
orbs:
  gimlet: gimlet-io/circleci-orb@dev:393d08b

workflows:
  master-build:
    jobs:
      - test: {}
      - build_docker:
          requires:
            - test
      - gimlet/gimlet-artifact-push:
          requires:
            - build_docker

jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo test

  build_docker:
    docker:
      - image: cimg/base:2021.04
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout
      - run:
          name: Building Docker image
          command: |
            echo docker
